### ISSUE TITLE
代码块显示不全异常

### ISSUE THREAD

**Issue by NAILIANGCHI** [amehime/hexo-theme-shoka#100]
![image](https://user-images.githubusercontent.com/85297838/230040207-cdaade03-7897-47da-b6bb-5a1f474468f3.png)
左上角三个点显示补全是什么原因？

**Comment by onon1101** [comment]
![image](https://user-images.githubusercontent.com/98307453/230713574-ad177532-1a72-4112-8e98-f4d1b9ea8379.png)
我也有出現這個問題

**Comment by NAILIANGCHI** [comment]
> 

还是没有解决方法，若您有解决方法请踢我一脚谢谢！😃🎉

**Comment by zkz098** [comment]
hexo highlights没关，参照下图关一下就行
![image](https://user-images.githubusercontent.com/92242020/230905823-b145a788-4389-4845-a402-531b40f4adda.png)

**Comment by NAILIANGCHI** [comment]
> 
您好，停用后还是没有解决这个问题

**Comment by zkz098** [comment]
`hexo clean`之后再试试，可能是hexo缓存问题

**Comment by NAILIANGCHI** [comment]
那三个点点没是没了，虽然没之前的好看就这样吧

**Comment by zkz098** [comment]
停用代码高亮之后应该会变成最正常的mac代码块才对()
如果样式变了可能是渲染器没正确接管代码高亮

**Comment by NAILIANGCHI** [comment]
> 停用代码高亮之后应该会变成最正常的mac代码块才对（） 如果样式变了可能是渲染器没正确接管代码高亮

![image](https://user-images.githubusercontent.com/85297838/230911846-c3f1cf4a-19c2-41c1-8e3c-7bb8837cbb89.png)
停用后就是这个样子

**Comment by zkz098** [comment]
> > 停用代码高亮之后应该会变成最正常的mac代码块才对（） 如果样式变了可能是渲染器没正确接管代码高亮
> 
> ![image](https://user-images.githubusercontent.com/85297838/230911846-c3f1cf4a-19c2-41c1-8e3c-7bb8837cbb89.png) 停用后就是这个样子


这个就是没有高亮，渲染器没正确接管
正常的禁用之后是这样的:
![image](https://user-images.githubusercontent.com/92242020/230912150-cab1a7c8-65d5-4cd1-aa12-32e24f602cc9.png)
建议重装MD渲染器试试

**Comment by NAILIANGCHI** [comment]
> 

![image](https://user-images.githubusercontent.com/85297838/230920999-e375cbd6-90ed-48dc-a5ca-bac37bd30e78.png)
是这个插件吗 ？

**Comment by zkz098** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/85297838/230920999-e375cbd6-90ed-48dc-a5ca-bac37bd30e78.png) 是这个插件吗 ？

是

**Comment by NAILIANGCHI** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/85297838/230920999-e375cbd6-90ed-48dc-a5ca-bac37bd30e78.png)是这个插件吗 ？
> 
> 是

昨天根据官方教程重新安装一遍和配置还是无法接管不知道是什么原因

**Comment by zkz098** [comment]
> 昨天根据官方教程重新安装一遍和配置还是无法接管不知道是什么原因

怪了，不应该这种情况，代码块的三个反引号后加raw了吗(如果没有语言)

根据生成的Html来看，你似乎忘记在反引号后加语言了，格式应该如下:
````markdown
```language
code
```
````

**Comment by NAILIANGCHI** [comment]
> > 昨天根据官方教程重新安装一遍和配置还是无法接管不知道是什么原因
> 
> 怪了，不应该这种情况，代码块的三个反引号后加raw了吗（如果没有语言）
> 
> 根据生成的Html来看，你似乎忘记在反引号后加语言了，格式应该如下：
> 
> ```gfm
> ```language
> code
> ```
> ```

非常感谢！根据您的提示我检查写的博客代码块语言开头大写导致渲染器不识别现在改为小写或者raw后可以正常显示😀😀😀

**Comment by moying688** [comment]
能

> > > 昨天根据官方教程重新安装一遍和配置还是无法接管不知道是什么原因
> > 
> > 
> > 怪了，不应该这种情况，代码块的三个反引号后加raw了吗（如果没有语言）
> > 根据生成的Html来看，你似乎忘记在反引号后加语言了，格式应该如下：
> > ```
> > ```language
> > code
> > ```
> 
> 非常感谢！根据您的提示我检查写的博客代码块语言开头大写导致渲染器不识别现在改为小写或者raw后可以正常显示😀😀😀

能问一下哥们，你解决完这个问题有没有出现识别不了Java或者其他语言的代码

**Comment by NAILIANGCHI** [comment]
您好！您的邮件我已经收到。阅读后尽快给您回复！

**Comment by moying688** [comment]
https://img2.imgtp.com/2024/03/19/BCKejbrp.png

**Comment by Orangenazuna** [comment]
> https://img2.imgtp.com/2024/03/19/BCKejbrp.png

如果不需要代码高亮，但希望显示代码块样式，则设为 raw

**Comment by Orangenazuna** [comment]
> 能
> 
> > > > 昨天根据官方教程重新安装一遍和配置还是无法接管不知道是什么原因
> > > 
> > > 
> > > 怪了，不应该这种情况，代码块的三个反引号后加raw了吗（如果没有语言）
> > > 根据生成的Html来看，你似乎忘记在反引号后加语言了，格式应该如下：
> > > ```
> > > ```language
> > > code
> > > ```
> > 
> > 
> > 非常感谢！根据您的提示我检查写的博客代码块语言开头大写导致渲染器不识别现在改为小写或者raw后可以正常显示😀😀😀
> 
> 能问一下哥们，你解决完这个问题有没有出现识别不了Java或者其他语言的代码

在默认情况下，markdown-it 支持的语言有：

JavaScript
CSS
HTML
Bash/Shell
Python
Java
C
C++
Ruby
PHP
SQL
JSON
Markdown

**Comment by NAILIANGCHI** [comment]
> 能
> 
> > > > 昨天根据官方教程重新安装一遍和配置还是无法接管不知道是什么原因
> > > 
> > > 
> > > 怪了，不应该这种情况，代码块的三个反引号后加raw了吗（如果没有语言）
> > > 根据生成的Html来看，你似乎忘记在反引号后加语言了，格式应该如下：
> > > ```
> > > ```language
> > > code
> > > ```
> > 
> > 
> > 非常感谢！根据您的提示我检查写的博客代码块语言开头大写导致渲染器不识别现在改为小写或者raw后可以正常显示😀😀😀
> 
> 能问一下哥们，你解决完这个问题有没有出现识别不了Java或者其他语言的代码

您好，我在使用的过程中没有出现识别不了的情况，可以发一下您的markdown 的页面看一下，另外在代码块设置语言类型的情况下不要大写
