### ISSUE TITLE
搜索框可以打开，但是无法搜索

### ISSUE THREAD

**Issue by couse1989** [amehime/hexo-theme-shoka#15]
这个主题真的很好看，由于我是个小白，摸索了一下午，目前有三个问题未解决，希望有人可以帮忙解答一下，谢谢！
1.搜索框可以打开，但是无法搜索，不知道是哪里配置有问题
2.文章中代码高亮不能正常显示，只显示边框
3.评论功能无法启用

**Comment by uncleacc** [comment]
我的搜索遇到同样的问题

**Comment by couse1989** [comment]
兄弟，我已经解决了，需要创建一个新的indeces和apikey，参考一下这个https://blog.csdn.net/qq_35479468/article/details/107335663发自我的 iPad------------------ 原始邮件 ------------------发件人: uncleacc  <notifications@github.com>发送时间: 2020年12月23日 13:34收件人: amehime/hexo-theme-shoka <hexo-theme-shoka@noreply.github.com>抄送: couse1989 <couse@hotmail.com>, Author <author@noreply.github.com>主题: 回复：[amehime/hexo-theme-shoka] 搜索框可以打开，但是无法搜索 (#15)
我的搜索遇到同样的问题

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/amehime/hexo-theme-shoka/issues/15#issuecomment-749944200",
"url": "https://github.com/amehime/hexo-theme-shoka/issues/15#issuecomment-749944200",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Fidelxyz** [comment]
@couse1989

然而我使用 `hexo-algoliasearch` 测试时，不需要另外创建 API Key，只要将 Admin API Key 填入 `adminApiKey` 就能正常进行索引的新建、删除操作了。

此外我注意到 Algolia 的 API Key 界面中，有以下描述：

> **Search-Only API Key**
>
> This is the public API key to use in your frontend code. This key is **only usable for search queries** and sending data to the Insights API.
>
> **Admin API Key**
>
> This is the ADMIN API key. Please keep it secret and use it ONLY from your backend: this key is used to **create, update and DELETE your indices.** You can also use it to manage your API keys.

所以 `apiKey` 应指仅有查询权限的公钥，`adminApiKey` 指带有增删改权限的私钥。

如果如您博客中所说将带有增删改权限的 Key 填入 `apiKey` 中，则该 Key 可在前端 js 中找到，可能会有数据库被修改的风险。

**Comment by couse1989** [comment]
@Fidelxyz 
谢谢兄弟提醒，我这边测试了一下，确实是像您所说的一样，这个Key可以在前端的 js 中被找到，由于自己是个电脑小白，并不知道这种的风险，今后会多学一些网络安全方面的知识，非常感想

**Comment by couse1989** [comment]
问题已经全部解决，非常感谢大家

1.搜索问题：可以参考楼上的 **Fidelxyz** 大神的方法，配置完 **algoliasearch** 的 **Key** 后，用 `hexo algolia` 命令生成索引

2.代码高亮问题：是我自己使用了错误语法导致，因为我是第一次用 **markdown**，用默认主题的时候我都是直接用 \`\`\`  把代码括起来使用的，但是更换成 **Shoka** 主题后就出问题了，后来在 \`\`\`  后面加上一个空格和语言标识就可以正常显示了

3.评论问题：配置好 **LeanCloud** 的 **appId** 和 **appKey** 后，我登录到 **LeanCloud** 网站，在 **设置 -> 安全中心 -> Web安全域名** 添加上我的**Blog域名**后就生效了
