### ISSUE TITLE
加载动画能否隐藏掉？

### ISSUE THREAD

**Issue by qq995473428** [amehime/hexo-theme-shoka#3]
切换其他tab在切回来的时候还加载动画，这样感觉体验有点难受

**Comment by amehime** [comment]
好啦，最新版已经加上开关了，[戳此](https://shoka.lostyu.me/computer-science/note/theme-shoka-doc/config/#加载动画)
我其实为了多看两眼猫咪才加上tab切换显示loading动画的_(:зゝ∠)_

**Comment by qq995473428** [comment]
> 好啦，最新版已经加上开关了，[戳此](https://shoka.lostyu.me/computer-science/note/theme-shoka-doc/config/#%E5%8A%A0%E8%BD%BD%E5%8A%A8%E7%94%BB)
> 我其实为了多看两眼猫咪才加上tab切换显示loading动画的_(:зゝ∠)_
好哦
