### ISSUE TITLE
bug：代码高亮问题

### ISSUE THREAD

**Issue by co-neco** [amehime/hexo-theme-shoka#34]
经测试，c++无法正常解析，渲染之后，只用简单的框来包围代码，c，bash，java都可以正常地被美化的代码框包围。

**Comment by co-neco** [comment]
代码框选择cpp即可，选c++识别不了。

**Comment by pigstar02** [comment]
要一个个改吗，有没有好方法

**Comment by co-neco** [comment]
> 要一个个改吗，有没有好方法

用notepad++打开你的文章保存的文件夹（posts文件夹），然后整个目录的``` c  统一换成```c++就可以了；
或者写个python脚本也可以。
