### ISSUE TITLE
首页轮播图设置

### ISSUE THREAD

**Issue by flottant** [amehime/hexo-theme-shoka#4]
添加首页轮播图设置，例如更换掉新浪图床。

**Comment by amehime** [comment]
好的，这个上次在博客那里已经答应两位小伙伴，等忙完这阵后，下一个版本会加上这样的设置

**Comment by amehime** [comment]
最新版已经添加，[配置戳此](https://shoka.lostyu.me/computer-science/note/theme-shoka-doc/config/#随机图库)
