### ISSUE TITLE
github actions部署报错

### ISSUE THREAD

**Issue by llxlr** [amehime/hexo-theme-shoka#53]
本地环境正常，在github actions下`hexo g`就报`type: 'unknown block tag: linksfile'`，好玄学
![Uploading 网页捕获_30-12-2021_212430_github.com.jpeg…]()
![Uploading 网页捕获_30-12-2021_21256_github.com.jpeg…]()

**Comment by THU-Pieris** [comment]
俺的本地环境也报这个错qaq求问怎么解决的
`Nunjucks Error: friends/index.md [Line 4, Column 5] unknown block tag: linksfile`
