### ISSUE TITLE
更换评论区为utteranc.es后pjax加载问题

### ISSUE THREAD

**Issue by THU-Pieris** [amehime/hexo-theme-shoka#60]
使用utteranc.es作为评论区之后，首次点进文章不会加载出评论，需要刷新一次才能出来。

我改动的地方为`layout/_macro/comment.njk`。

大概知道这个是和pjax有关的问题，但我不清楚要怎么修。全局搜索valine后照猫画虎地修了一下，没弄好。希望走过路过的大佬帮下忙，谢谢！

如果有需要的话，我fork并改动的主题仓库地址: https://github.com/THU-Pieris/hexo-theme-shoka

**Comment by llxlr** [comment]
[script](https://github.com/THU-Pieris/hexo-theme-shoka/blob/a2ebcf1c8c4fa827fb50396282a269a906205196/layout/_macro/comment.njk#L10) 里加上`data-pjax`属性可以吗

```js
  <script src="https://utteranc.es/client.js"
    repo="THU-Pieris/blog-comment"
    issue-term="title"
    label="hexo"
    theme="preferred-color-scheme"
    crossorigin="anonymous"
    async
    data-pjax>
  </script>
```

**Comment by THU-Pieris** [comment]
> ```js
> data-pjax
> ```

唔，还是不太行。不过还是谢谢您！
