### ISSUE TITLE
leancloud+valine-admin 评论系统无法正常使用

### ISSUE THREAD

**Issue by 0x401000Nu1l** [amehime/hexo-theme-shoka#61]
按照主体作者的步骤，设置了leancloud应用以及部署了valine-admin后，个人博客主页出现了评论区但是评论编辑完之后点击submit无响应，并且leancloud后台也没有收到评论详细截图如下
下

![image](https://user-images.githubusercontent.com/94042101/161214784-d1c1ce7f-b77d-4dba-ba5e-cecd87df004a.png)
![image](https://user-images.githubusercontent.com/94042101/161214873-f36d8819-64ba-4781-ad5e-f93d04e43964.png)
![image](https://user-images.githubusercontent.com/94042101/161214959-fd9737ae-ed3a-4157-96f0-7474e26f9ebd.png)

**Comment by llxlr** [comment]
`serverURLs`里加上`https://`前缀
