### ISSUE TITLE
图床(image_server)自定义无效

### ISSUE THREAD

**Issue by Feafortecsy** [amehime/hexo-theme-shoka#7]
1. `image_server`设置为`https://acg.xydwz.cn/api/api.php`无效，出现的自定义图片还是`_images.yal`里面的。
另外我debug的时候发现`hexo-theme-shoka/scripts/helpers/engine.js`文件第18行这一部分逻辑并没有进入，接下来不知道怎么查问题，只能麻烦下博主了
2. 如果将`_images.yml`文件的内容都删除(因为想着配置了`image_server`就不需要`_images.yal`了)会因为找不到图片报错，即使设置了`image_server`也是如此，[查看](https://github.com/amehime/hexo-theme-shoka/pull/6)
3. Gitee发现两个仓库不知道什么情况
- [kiloGrand/hexo-theme-shoka](https://gitee.com/flottant/hexo-theme-shoka?_from=gitee_search)
- [flottant/hexo-theme-shoka](https://gitee.com/kiloGrand/hexo-theme-shoka?_from=gitee_search)

**Comment by amehime** [comment]
1. 我测试了两遍，好像并没有失效的问题（捂脸
如果逻辑没有进入的话，那还是`image_server`的值为空了，还是检查一下配置文件什么的？
2. 如果`image_server`配置正确了的话，`_image.yml`的内容确实可以删掉不会报错的，所以还是检查一下配置文件吗
3. gitee上不知道，我没有上传到gitee，大概有热心人fork的吧，蛤蛤蛤
