### ISSUE TITLE
无法解决的报错

### ISSUE THREAD

**Issue by Ezgx** [amehime/hexo-theme-shoka#74]
![image](https://user-images.githubusercontent.com/110729988/201246982-07333fef-83d6-4b0e-a297-b46f1f6b18ea.png)

**Comment by zunley** [comment]
@echocbx 
maybe you don't have the `pangu` node_module installed.

**Comment by Ezgx** [comment]
> @echocbx maybe you don't have the `pangu` node_module installed.

ok
