### ISSUE TITLE
怎么更改主页图片

### ISSUE THREAD

**Issue by Ezgx** [amehime/hexo-theme-shoka#77]
如题
![图片](https://user-images.githubusercontent.com/110729988/203722280-a8924dbc-f756-4414-9b7a-36105b138f13.png)

**Comment by UniStart2** [comment]
[Yume Shoka 基本配置-随机图库](https://shoka.lostyu.me/computer-science/note/theme-shoka-doc/config/#%E9%9A%8F%E6%9C%BA%E5%9B%BE%E5%BA%93)里面说的很清楚了，你确保你覆盖的图片数量在6以上基本就ok了

**Comment by Ezgx** [comment]
> [Yume Shoka 基本配置-随机图库](https://shoka.lostyu.me/computer-science/note/theme-shoka-doc/config/#%E9%9A%8F%E6%9C%BA%E5%9B%BE%E5%BA%93)里面说的很清楚了，你确保你覆盖的图片数量在6以上基本就ok了

谢谢
