### ISSUE TITLE
优化中国大陆地区访问速度

### ISSUE THREAD

**Issue by flottant** [amehime/hexo-theme-shoka#8]
Polyfill.js 加载缓慢。
valine 评论区头像无法加载。

**Comment by amehime** [comment]
诶，我这边江苏电信，一切还算OK。。
头像的话已经是用的loli.net国内加速服务地址了（捂脸
然后polyfill的话，如果实在不行就自己搭个[这个](https://github.com/Financial-Times/polyfill-service)

**Comment by flottant** [comment]
经过站长之家的测试，中国移动网络似乎无法正确打开 gravatar.loli.net 头像服务。
