### ISSUE TITLE
如何替换掉当前主题下的代码块渲染呢

### ISSUE THREAD

**Issue by EvilMoOd** [amehime/hexo-theme-shoka#81]
当前主题的代码块个人不太中意且部分语言无法高亮，能否简单进行配置替换

**Comment by zkz098** [comment]
这个比较复杂,因为代码高亮依赖于markdown渲染器,修改是肯定要改代码的,而且修改代码量不会很小
能否把无法高亮的语言发出来,理论上prism.js支持的语言都能高亮

**Comment by EvilMoOd** [comment]
css代码无法高亮
目前我通过启用highlight然后修改主题css文件实现了我的需求

**Comment by zkz098** [comment]
CSS应该可以高亮:
![image](https://user-images.githubusercontent.com/92242020/213911981-e1a56469-1532-4554-9054-63dc7dd607f2.png)
