### ISSUE TITLE
博客评论头像加载不出来

### ISSUE THREAD

**Issue by UniStart2** [amehime/hexo-theme-shoka#86]
[![mxXix.md.png](https://i.328888.xyz/2023/02/15/mxXix.md.png)](https://imgloc.com/i/mxXix)
如图所示，评论系统使用的是gravatar作为头像，但是gravatar记载不出来，我想换成国内的cravatar，感觉可能快一点，但是不知道怎么弄，有大佬会么？

**Comment by zkz098** [comment]
改minivaline文件，把minivaline下载下来之后把`gravatar.loli.net`批量替换就行

**Comment by UniStart2** [comment]
谢谢大佬，已经解决了

**Comment by modiqi** [comment]
我们新建了一个 Hexo 的仓库，后面会提供下 hexo 的 Cravatar 头像使用文档。 

https://github.com/Cravatar/hexo-cravatar

**Comment by zkz098** [comment]
> 我们新建了一个 Hexo 的仓库，后面会提供下 hexo 的 Cravatar 头像使用文档。
> 
> https://github.com/Cravatar/hexo-cravatar

此问题是评论系统(魔改的minivaline)对Cravatar的支持不佳导致的，和Hexo集成应该关系不大
