### ISSUE TITLE
封面图片本地显示的出来 部署后显示不出来

### ISSUE THREAD

**Issue by maoding1** [amehime/hexo-theme-shoka#87]
![image](https://user-images.githubusercontent.com/91577173/220132922-7b33f1db-70ab-4961-a76d-93df202d7b45.png)
如图 打开图片链接会显示403 forbidden

**Comment by hy6xing** [comment]
你路径用的是图床链接还是本地目录？

**Comment by maoding1** [comment]
> 

用的是新浪图床 刚查了好像是图床问题 但是怎么解决？

**Comment by couse1989** [comment]
该项目图床用的是新浪(已失效),我是自己创建一个images.yml文件,然后添加自定义的图片链接,请参考作者博客中的文档操作 https://shoka.lostyu.me/computer-science/note/theme-shoka-doc/config/#%E9%9A%8F%E6%9C%BA%E5%9B%BE%E5%BA%93

**Comment by maoding1** [comment]
谢谢 不过我也刚好暂时解决 同根据作者博客下方下的评论 把themes\shoka\scripts\helpers下的engine.js的第三十一行改成了 return 'https://lz.sinaimg.cn/'+size+'/'+img

**Comment by hy6xing** [comment]
新浪早就不能做图床了，会被封的。我的新浪账号就是被了，发不了任何东西。图床的话可以用smms,等。可以管理图片。也可以不牛图等不可以管理图片

**Comment by couse1989** [comment]
如果问题已经解决了，还麻烦把问题关闭掉，养成一个良好习惯

**Comment by maoding1** [comment]
好的好的 其实只算暂时解决 不过以后要是也挂了也知道怎么改了
